#!/bin/sh -e

#	Simple build and install script
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo ""
    exit 1
  fi
}

sudo=${LIB_KA_RS485_SUDO-sudo}

echo "libka_rs485 Build script"
echo "====================="
echo

$sudo rm -rf build
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
check_make_ok
$sudo make install
check_make_ok


echo
echo All Done.
echo ""
echo "NOTE: To compile programs with libka_rs485, you need to add:"
echo "    -lka_rs485"
echo "  to your compile line(s)"
echo ""
